name: Keep runners alive

on:
  schedule:
    - cron: '0 12 */4 * *'

permissions:
  id-token: write
  contents: read

jobs:
  start:
    if: github.repository == 'mockingbirdnest/Principia'
    runs-on: windows-latest
    steps:
    - name: Start runners
      uses: mockingbirdnest/actions/windows/start_runners@main
      with:
        client_id: ${{ secrets.PRINCIPIA_BUILD_CLIENT_ID }}
        tenant_id: ${{ secrets.PRINCIPIA_BUILD_TENANT_ID }}
        subscription_id: ${{ secrets.PRINCIPIA_BUILD_SUBSCRIPTION_ID }}

